In [236]:
import os
import numpy as np
from sklearn.utils import shuffle
from PIL import Image


call_folder = '/home/dario/Documents/SemThes_Local/Data_32_32'

batch_size = 39

X_train = np.load(os.path.join(call_folder, 'X_train.npy'))
y_train = np.load(os.path.join(call_folder, 'y_binned_train.npy'))[:, 0:1, 0:1] # NUMERISCHER WERT - ÄNDERN!
print(y_train.shape)

row, col, _ = np.array(Image.open(str(X_train[0]))).shape

for i in range(0, int(np.floor(len(X_train)/batch_size)) + 1):
    if i == (int(np.floor(len(X_train)/batch_size))):
        batch_size = len(X_train) - (i * batch_size)

    X = np.full((batch_size, row, col, 1), 0, dtype = np.uint8)
    
    for k in range(0, batch_size):
        img = np.array(Image.open(str(X_train[k + i * batch_size])))
        X[k, :, :, :] = img[:,:,0:1] # NUMERISCHER WERT - ÄNDERN!
    y = y_train[i * batch_size:(i + 1) * batch_size]
        

(240, 1, 1)


In [2]:
import os
import numpy as np
from sklearn.utils import shuffle
from PIL import Image

def batch_generator(X, y, batch_size):

    row, col, _ = np.array(Image.open(str(X[0]))).shape

    for i in range(0, int(np.floor(len(X) / batch_size)) + 1):
        if i == (int(np.floor(len(X) / batch_size))):
            batch_size = len(X) - (i * batch_size)

        X_send = np.full((batch_size, row, col, 1), 0, dtype = np.uint8)
        
        for k in range(0, batch_size):
            img = np.array(Image.open(str(X[k + i * batch_size])))
            X_send[k, :, :, :] = img[:,:,0:1]       # NUMERISCHER WERT - ÄNDERN!
        y_send = y[i * batch_size:(i + 1) * batch_size]

        (X_send, y_send) = shuffle(X_send, y_send)

        yield(X_send, y_send)
        
def batch_generator_V1(X, y, batch_size):

    row, col = X[0].shape

    for i in range(0, int(np.floor(len(X) / batch_size)) + 1):
        if i == (int(np.floor(len(X) / batch_size))):
            batch_size = len(X) - (i * batch_size)

        X_send = np.full((batch_size, row, col, 1), 0, dtype = np.uint8)
        
        for k in range(0, batch_size):
            img = np.array(Image.open(str(X[k + i * batch_size])))
            X_send[k, :, :, :] = img[:,:,0:1]       # NUMERISCHER WERT - ÄNDERN!
        y_send = y[i * batch_size:(i + 1) * batch_size]

        (X_send, y_send) = shuffle(X_send, y_send)

        yield(X_send, y_send)

def batch_generator_V2(X, y, batch_size):
       
    for i in range(0, X.shape[0], batch_size):
        yield (X[i:i+batch_size, :], y[i:i+batch_size])
        


In [16]:
batch_size = 2

call_folder = '/home/dario/Documents/SemThes_Local/Data_32_32'
X_train = np.load(os.path.join(call_folder, 'bla.npy'))
y_train = np.load(os.path.join(call_folder, 'blabla.npy'))

batch_gen = batch_generator(X_train, y_train, batch_size)
for i, (batch_x, batch_y) in enumerate(batch_gen):
    print(batch_x, batch_y)

FileNotFoundError: [Errno 2] No such file or directory: '[0.80876375 0.09838604]'

In [18]:
batch_size = 2

X = np.random.rand(10,2)
y = np.random.rand(10,1)
for i in range(0, X.shape[0], batch_size):
    print(X[i:i+batch_size, :])
    print(y[i:i+batch_size])
        
print()
batch_gen = batch_generator_V2(X, y, batch_size)
for i, (batch_x, batch_y) in enumerate(batch_gen):
    print(batch_x)
    print()
    print(batch_y)
    print()
    print()

[[0.47298192 0.66267732]
 [0.02536783 0.83580527]]
[[0.08369799]
 [0.18703984]]
[[0.21840918 0.78434386]
 [0.14068412 0.88391535]]
[[0.29276732]
 [0.2492911 ]]
[[0.68676126 0.79176233]
 [0.71634847 0.47837818]]
[[0.380735  ]
 [0.83706598]]
[[0.49154645 0.65532662]
 [0.14947773 0.86857986]]
[[0.12732461]
 [0.71822903]]
[[0.93359152 0.34853057]
 [0.97158186 0.59572668]]
[[0.10938192]
 [0.69347608]]

[[0.47298192 0.66267732]
 [0.02536783 0.83580527]]

[[0.08369799]
 [0.18703984]]


[[0.21840918 0.78434386]
 [0.14068412 0.88391535]]

[[0.29276732]
 [0.2492911 ]]


[[0.68676126 0.79176233]
 [0.71634847 0.47837818]]

[[0.380735  ]
 [0.83706598]]


[[0.49154645 0.65532662]
 [0.14947773 0.86857986]]

[[0.12732461]
 [0.71822903]]


[[0.93359152 0.34853057]
 [0.97158186 0.59572668]]

[[0.10938192]
 [0.69347608]]




In [14]:
X = np.random.rand(10,2)
y = np.random.rand(10,1)

np.save('bla.npy', X)
np.save('blabla.npy', y)
